### PR TITLE
Cart model

### PR DESCRIPTION
**Pull request by radubpopescu**
yoyoyo, added a cart model with a working cart show view. 

if you guys have time, pull my branch and test to see if all ok.

otherwise, let's talk tuesday. 

cheerios

### CODE REVIEW

**Comment by bedhabits** [comment]
I guess there is a missing view yet for the checkout, right ? Cause I get this error when try to chekcout: 
"OrdersController#new is missing a template for this request format and variant"

**Comment by radubpopescu** [comment]
yep, that is true, will try today to make the orders controller work as well :)

**Comment by radubpopescu** [comment]
fixed it now, you guys can check :)

**Comment by radubpopescu** [comment]
image
image
image

**Comment by bedhabits** [comment]
So, should we change Cart model to Order Model ? I don't know if we need both, right ?

**Pull request merged**
